Fix Typescript Mismatch
Currently, there's a mismatch with `@types/jasmine` that throws the following error:
```
node_modules/@types/jasmine/index.d.ts(404,15): error TS2428: All declarations of 'Matchers' must have identical type parameters.
node_modules/jasmine-expect/jasmine-matchers.d.ts(2,13): error TS2428: All declarations of 'Matchers' must have identical type parameters.
```
this adjustment fix the Typescript definitions of the project. Refs #62